// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tribuo-core-impl.proto

package org.tribuo.protos.core;

public interface HashCodeHasherProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tribuo.core.HashCodeHasherProto)
    com.google.protobuf.MessageOrBuilder {
}
